# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE
# This file was automatically generated by Natron PyPlug exporter version 10.

# Hand-written code should be added in a separate file named DecryptomatteAllExt.py
# See http://natron.readthedocs.org/en/master/groups.html#adding-hand-written-code-callbacks-etc
# Note that Viewers are never exported

import NatronEngine
import sys

# Try to import the extensions file where callbacks and hand-written code should be located.
try:
    from DecryptomatteAllExt import *
except ImportError:
    pass

try:
    from CryptomatteExt import *
except ImportError:
    pass

def getPluginID():
    return "com.Cryptomatte.pyplug.DecryptomatteAll"

def getLabel():
    return "DecryptomatteAll"

def getVersion():
    return 1

def getIconPath():
    return "cryptomatte_logo.png"

def getGrouping():
    return "Keyer/Cryptomatte"

def getPluginDescription():
    return "This plugin can be used to convert all Cryptomatte nodes into expressions."

def getIsToolset():
    return True

def createInstance(app,group):
    print "Called DecryptomatteAll"
    decryptomatte_all(app)
    